spring.application.name=backend
server.port=8080

spring.mongodb.database=hospital_management_db
spring.mongodb.host=localhost
spring.mongodb.port=27017

logging.level.org.springframework.security=DEBUG